'use client'
import { useRef, useState, type ChangeEvent } from 'react'
import { ArrowDown, ArrowRight, ImagePlus, Pencil, Plus, Sparkles, Trash2, X } from 'lucide-react'

type Memory = { id:number; year:string; title:string; text:string; axis:string; color:string; image?:string }
const milestones = [
 ['2006','Nace un derecho','Ley Nacional 26.150 reconoce el derecho a recibir ESI.','EL DERECHO'],['2008','La ESI llega a las aulas','Lineamientos Curriculares orientan su enseñanza.','ENSEÑAR'],['2010','Se amplían derechos','El matrimonio igualitario transforma el horizonte de igualdad.','IGUALDAD'],['2012','Derecho a la identidad','La Ley de Identidad de Género amplía el reconocimiento.','IDENTIDAD'],['2015','La Provincia suma su ley','La Ley Provincial 14.744 reconoce la ESI en Buenos Aires.','BUENOS AIRES'],['2018','Nuevos lineamientos','La Resolución CFE 340/18 fortalece los cinco ejes.','5 EJES'],['2019','Educación y prevención','La Ley Micaela impulsa formación para prevenir violencias.','APRENDER'],['2022','La ESI continúa','La Resolución CFE 419/22 invita a seguir construyendo.','CONSTRUIR']]
const axes = ['Cuidar el cuerpo y la salud','Valorar la afectividad','Garantizar la equidad de género','Respetar la diversidad sexual','Ejercer nuestros derechos']
const colors = ['#f5d963','#b9e3d2','#f5c1ad','#c9c3ee']

export function HistoryMuseum(){
 const timeline=useRef<HTMLDivElement>(null); const [open,setOpen]=useState<number|null>(null); const [memories,setMemories]=useState<Memory[]>([]); const [formOpen,setFormOpen]=useState(false); const [editing,setEditing]=useState<number|null>(null); const [axis,setAxis]=useState(0); const [message,setMessage]=useState(''); const [saved,setSaved]=useState(false); const [form,setForm]=useState<Memory>({id:0,year:'2026',title:'',text:'',axis:axes[0],color:colors[0]})
 const reset=()=>{setForm({id:0,year:'2026',title:'',text:'',axis:axes[0],color:colors[0]});setEditing(null);setFormOpen(false)}
 const image=(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>setForm(f=>({...f,image:String(reader.result)}));reader.readAsDataURL(file)}
 const save=()=>{if(!form.title.trim()||!form.text.trim())return;setMemories(m=>editing?m.map(x=>x.id===editing?form:x):[...m,{...form,id:Date.now()}]);reset()}
 return <div className="bg-[#fbfaf7] text-[#132f3b]">
  <section className="relative overflow-hidden bg-[#286f60] px-5 py-20 text-white lg:px-10 lg:py-28"><div className="mx-auto grid max-w-7xl items-end gap-12 lg:grid-cols-[1fr_.7fr]"><div><p className="text-sm font-black uppercase tracking-[.25em] text-[#f5d963]">ESI 20 AÑOS · Nuestra historia</p><h1 className="mt-5 text-6xl font-black leading-[.9] tracking-[-.07em] sm:text-8xl">20 años<br/><span className="text-[#f5d963]">haciendo escuela.</span></h1><p className="mt-8 max-w-xl text-lg leading-relaxed text-[#d7eee3]">La ESI es una construcción colectiva. Recorré las conversaciones, aprendizajes y conquistas que nos trajeron hasta acá.</p><button onClick={()=>timeline.current?.scrollIntoView({behavior:'smooth'})} className="mt-9 rounded-full bg-[#e68a55] px-6 py-3.5 font-black">COMENZAR EL RECORRIDO <ArrowDown className="ml-2 inline size-4"/></button></div><div className="rounded-[2.5rem] bg-[#f5d963] p-8 text-center text-[#286f60] shadow-2xl rotate-3"><div className="mx-auto flex size-32 items-center justify-center rounded-full border-4 border-[#286f60] text-2xl font-black leading-none">ESI<br/>20<br/>AÑOS</div><p className="mt-5 text-2xl font-black">Nuestra escuela,<br/>nuestras huellas.</p><Sparkles className="mx-auto mt-4"/></div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-16 lg:px-10"><div className="grid gap-6 rounded-[2rem] bg-white p-8 shadow-sm ring-1 ring-[#e1e9e3] md:grid-cols-[1fr_auto] md:items-center"><div><p className="text-sm font-black uppercase tracking-[.2em] text-[#e68a55]">¿Por qué hacemos este recorrido?</p><h2 className="mt-3 text-3xl font-black text-[#286f60]">La historia vive en lo cotidiano.</h2><p className="mt-3 max-w-2xl leading-relaxed text-[#64756e]">La ESI se construye en las aulas, los proyectos, las preguntas y las conversaciones.</p></div><div className="flex gap-3 text-3xl">💬 📚 🤝 ⚖️ 🏫</div></div></section>
  <section ref={timeline} className="mx-auto max-w-7xl scroll-mt-20 px-5 pb-20 lg:px-10"><p className="text-sm font-black uppercase tracking-[.2em] text-[#e68a55]">Línea de tiempo</p><h2 className="mt-2 text-5xl font-black text-[#286f60]">Un recorrido compartido</h2><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{milestones.map((m,i)=><button key={m[0]} onClick={()=>setOpen(open===i?null:i)} className={`rounded-[1.7rem] p-6 text-left transition ${open===i?'bg-[#286f60] text-white shadow-xl':'bg-white ring-1 ring-[#e1e9e3] hover:-translate-y-1'}`}><span className={`text-4xl font-black ${open===i?'text-[#f5d963]':'text-[#e68a55]'}`}>{m[0]}</span><p className={`mt-5 text-xs font-black uppercase tracking-widest ${open===i?'text-[#f5d963]':'text-[#e68a55]'}`}>{m[3]}</p><h3 className="mt-2 text-xl font-black">{m[1]}</h3>{open===i&&<p className="mt-4 border-t border-white/20 pt-4 text-sm leading-relaxed text-[#d7eee3]">{m[2]} <ArrowRight className="ml-1 inline size-4"/></p>}</button>)}</div></section>
  <section className="bg-[#132f3b] px-5 py-20 text-center text-white lg:px-10"><p className="text-sm font-black uppercase tracking-[.2em] text-[#f5d963]">La historia también se construye acá</p><h2 className="mt-4 text-5xl font-black">¿Y qué pasó en nuestra escuela?</h2><p className="mx-auto mt-5 max-w-xl text-[#c8dcd4]">No inventamos respuestas: las construimos entre todas las voces.</p></section>

  <section className="bg-[#e4f0e9] px-5 py-20 lg:px-10"><div className="mx-auto max-w-7xl"><h2 className="text-5xl font-black text-[#286f60]">Los cinco ejes como mapa</h2><div className="mt-8 grid gap-3 md:grid-cols-5">{axes.map((a,i)=><button key={a} onClick={()=>setAxis(i)} className={`rounded-2xl p-5 text-left font-black ${axis===i?'bg-[#f5d963] text-[#286f60]':'bg-white text-[#286f60]'}`}><span className="text-3xl">0{i+1}</span><span className="mt-6 block text-sm">{a}</span></button>)}</div><p className="mt-6 rounded-2xl bg-white p-6 text-[#64756e]">Este eje nos invita a hacer preguntas, escuchar otras voces y sumar nuevas huellas.</p></div></section>
  <section className="mx-auto max-w-7xl px-5 py-20 lg:px-10"><div className="grid gap-8 rounded-[2rem] bg-[#f5d963] p-8 md:grid-cols-2 md:p-12"><div><p className="text-sm font-black uppercase tracking-[.2em] text-[#286f60]">2026 → 2036</p><h2 className="mt-3 text-5xl font-black text-[#286f60]">Mensaje para la escuela de 2036</h2><p className="mt-4 text-[#426259]">¿Qué escuela queremos construir?</p></div><div><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Imaginá que alguien abre este mural dentro de diez años..." rows={5} className="w-full rounded-2xl border-0 bg-white/70 p-4"/><button onClick={()=>setSaved(true)} className="mt-4 rounded-full bg-[#286f60] px-5 py-3 font-black text-white">{saved?'Tu huella quedó guardada':'Sumar mi idea'}</button></div></div></section>

 </div>
}
