'use client'

import { useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, BookOpen, Check, ChevronRight, CircleHelp, Clock3, Compass, GalleryHorizontalEnd, HeartHandshake, Lightbulb, Menu, Sparkles, Target, Users, X } from 'lucide-react'
import { actividades, buildQuiz, ejeById, ejes, type ActivityId, type EjeId, quizModes, timeline, cursos, type QuizMode } from '@/data/preguntasESI'

type Screen = 'home' | 'onboarding' | 'dashboard' | 'axes' | 'quiz' | 'timeline'

const Logo = () => <img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/logo%20sin%20fondo-OfG31oVwHYMBTUJhtpQsQbdIp62QcL.png" alt="E.E.S.T. N.º 6 Ing. Juan V. Passalacqua" className="school-logo" />

const Header = ({ onHome, onMenu, course }: { onHome: () => void; onMenu: () => void; course?: string }) => <header className="topbar"><button className="brand" onClick={onHome}><Logo /><span><strong>E.E.S.T. N.º 6</strong><small>Ing. Juan V. Passalacqua · Banfield</small></span></button><div className="top-actions">{course && <span className="course-pill">Curso {course}</span>}<button className="icon-button" aria-label="Abrir menú" onClick={onMenu}><Menu /></button></div></header>

export default function EsiApp() {
  const [screen, setScreen] = useState<Screen>('home')
  const [course, setCourse] = useState('')
  const [year, setYear] = useState('')
  const [menuOpen, setMenuOpen] = useState(false)
  const [activity, setActivity] = useState<ActivityId | null>(null)
  const [quizMode, setQuizMode] = useState<QuizMode>('all')
  const [selectedEje, setSelectedEje] = useState<EjeId | undefined>()
  const [quiz, setQuiz] = useState<any[]>([])
  const [current, setCurrent] = useState(0)
  const [answers, setAnswers] = useState<number[]>([])
  const [selected, setSelected] = useState<number | null>(null)

  const start = () => { if (course) setScreen('dashboard') }
  const beginQuiz = (mode: QuizMode, eje?: EjeId) => { setQuizMode(mode); setSelectedEje(eje); setQuiz(buildQuiz(mode, eje)); setCurrent(0); setAnswers([]); setSelected(null); setScreen('quiz'); setActivity('quiz') }
  const answer = (index: number) => { if (selected === null) { setSelected(index); setAnswers((prev) => [...prev, index]) } }
  const next = () => { if (current < quiz.length - 1) { setCurrent((n) => n + 1); setSelected(null) } else setScreen('dashboard') }
  const score = useMemo(() => answers.reduce((total, answer, index) => total + (quiz[index]?.respuestaCorrecta === answer ? 1 : 0), 0), [answers, quiz])

  if (screen === 'home') return <main className="app-shell home-screen"><div className="noise" /><Header onHome={() => setScreen('home')} onMenu={() => setMenuOpen(true)} /><div className="home-grid"><section className="hero-copy"><div className="eyebrow"><span className="live-dot" /> Experiencia interactiva · 2026</div><h1>ESI<br /><em>20 años</em></h1><p className="hero-subtitle">Nuestra escuela,<br />nuestras huellas.</p><p className="hero-description">20 años de derechos, aprendizajes, encuentros y desafíos. Recorré, pensá, jugá y creá para descubrir qué significa la ESI en nuestra escuela.</p><button className="primary-button" onClick={() => setScreen('onboarding')}>COMENZAR <ArrowRight /></button></section><section className="hero-visual"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="year-mark"><span>20</span><small>AÑOS DE<br />ESI</small></div><div className="floating-card card-top"><Sparkles /><span>Derechos<br /><b>que dejan huella</b></span></div><div className="floating-card card-bottom"><span className="mini-index">05</span><span>ejes para<br /><b>transformar</b></span></div><div className="hero-quote">"La ESI también se construye<br />con nuestras acciones."</div></section></div><footer className="home-footer"><span>EDUCACIÓN · PARTICIPACIÓN · FUTURO</span><span>Banfield — Lomas de Zamora</span></footer>{menuOpen && <MenuPanel close={() => setMenuOpen(false)} />}</main>

  if (screen === 'onboarding') return <main className="app-shell onboarding"><Header onHome={() => setScreen('home')} onMenu={() => setMenuOpen(true)} /><div className="onboarding-wrap"><div className="step-label">PRIMER PASO <span>01 / 02</span></div><h2>¿Quién<br /><em>participa?</em></h2><p className="muted">Elegí tu año y división para comenzar el recorrido de tu curso.</p><div className="field-block"><label>AÑO</label><div className="choice-grid years">{['1°','2°','3°','4°','5°','6°','7°'].map((item) => <button key={item} className={year === item ? 'choice selected' : 'choice'} onClick={() => setYear(item)}>{item}</button>)}</div></div><div className="field-block"><label>DIVISIÓN</label><select value={course} onChange={(event) => setCourse(event.target.value)}><option value="">Seleccioná tu división</option>{cursos.filter((item) => !year || item.startsWith(year)).map((item) => <option key={item}>{item}</option>)}</select></div><button className="primary-button" disabled={!course} onClick={start}>ENTRAR AL RECORRIDO <ArrowRight /></button></div></main>

  if (screen === 'quiz') { const q = quiz[current]; const axis = ejeById(q.eje); return <main className="app-shell quiz-screen"><Header course={course} onHome={() => setScreen('dashboard')} onMenu={() => setMenuOpen(true)} /><div className="quiz-wrap"><div className="quiz-header"><button className="back-link" onClick={() => setScreen('dashboard')}><ArrowLeft /> Salir del desafío</button><span>{current + 1} <i>/</i> {quiz.length}</span></div><div className="progress-line"><span style={{ width: `${((current + 1) / quiz.length) * 100}%` }} /></div><div className="quiz-meta"><span style={{ color: axis.color }}>{axis.icon} {axis.title}</span><span><Clock3 /> {q.dificultad}</span></div><h2>{q.pregunta}</h2><div className="answers">{q.opciones.map((option: string, index: number) => <button key={option} disabled={selected !== null} className={`answer ${selected !== null && index === q.respuestaCorrecta ? 'correct' : ''} ${selected === index && index !== q.respuestaCorrecta ? 'wrong' : ''}`} onClick={() => answer(index)}><span>{String.fromCharCode(65 + index)}</span>{option}{selected !== null && index === q.respuestaCorrecta && <Check />}</button>)}</div>{selected !== null && <div className="explanation"><div className="explain-icon"><Lightbulb /></div><div><strong>Para pensar</strong><p>{q.explicacion}</p></div></div>}<div className="quiz-footer"><span>Desafío {quizMode === 'all' ? 'Toda la ESI' : quizMode === 'five' ? 'Cinco ejes' : quizMode === 'full' ? 'Completo' : axis.short}</span><button className="primary-button" disabled={selected === null} onClick={next}>{current === quiz.length - 1 ? 'VER RESULTADO' : 'SIGUIENTE'} <ArrowRight /></button></div></div></main> }

  return <main className="app-shell dashboard"><Header course={course} onHome={() => setScreen('home')} onMenu={() => setMenuOpen(true)} /><div className="dashboard-wrap"><div className="welcome-row"><div><div className="eyebrow">RECORRIDO ESI · 20 AÑOS</div><h2>Hola, <em>{course}</em>.</h2><p>Tu recorrido empieza acá. Explorá, participá y dejá tu huella.</p></div><div className="progress-ring"><strong>0%</strong><span>recorrido</span></div></div><section className="dashboard-hero"><div><span className="section-kicker">LA ESCUELA QUE QUEREMOS</span><h3>¿Qué huella<br /><em>querés dejar?</em></h3><p>Hay muchas formas de participar. Elegí una actividad y construyamos juntos nuevas conversaciones.</p></div><div className="hero-stamp">20<br /><small>AÑOS</small></div></section><div className="section-heading"><div><span className="section-kicker">01 — 08</span><h3>Tu recorrido</h3></div><span className="muted">Elegí una estación para explorar</span></div><div className="activity-grid">{actividades.map(([number, title, text, id]) => <button key={id} className={`activity-card activity-${number}`} onClick={() => id === 'quiz' ? setScreen('axes') : id === 'timeline' ? setScreen('timeline') : setActivity(id)}><span className="activity-number">{number}</span><span className="activity-icon">{id === 'quiz' ? <Target /> : id === 'mural' ? <Users /> : id === 'timeline' ? <Clock3 /> : id === 'galeria' ? <GalleryHorizontalEnd /> : id === 'ideas' ? <Lightbulb /> : id === 'futuro' ? <Compass /> : <HeartHandshake />}</span><strong>{title}</strong><small>{text}</small><ChevronRight className="activity-arrow" /></button>)}</div><section className="axis-preview"><div className="section-heading"><div><span className="section-kicker">LOS 5 EJES</span><h3>Las ideas que nos mueven</h3></div><button className="text-button" onClick={() => setScreen('axes')}>Ver los cinco ejes <ArrowRight /></button></div><div className="axis-strip">{ejes.map((eje) => <button key={eje.id} style={{ '--axis-color': eje.color } as React.CSSProperties} onClick={() => { setSelectedEje(eje.id); setScreen('axes') }}><span>{eje.icon}</span><small>{eje.short}</small></button>)}</div></section></div>{(activity && activity !== 'quiz') && <ActivityModal id={activity} close={() => setActivity(null)} />}{menuOpen && <MenuPanel close={() => setMenuOpen(false)} />}</main>
}

function MenuPanel({ close }: { close: () => void }) { return <div className="menu-overlay" onClick={close}><aside className="menu-panel" onClick={(event) => event.stopPropagation()}><button className="close-button" onClick={close}><X /></button><span className="section-kicker">NAVEGACIÓN</span><h2>Tu recorrido<br /><em>ESI 20 años</em></h2>{['Inicio', 'Los 5 ejes', 'Galería de producciones', 'Nuestra memoria'].map((item) => <button key={item} onClick={close}>{item}<ArrowRight /></button>)}<div className="menu-bottom">E.E.S.T. N.º 6<br /><small>Ing. Juan V. Passalacqua</small></div></aside></div> }
function ActivityModal({ id, close }: { id: ActivityId; close: () => void }) { const item = actividades.find((activity) => activity[3] === id); return <div className="modal-overlay"><div className="activity-modal"><button className="close-button" onClick={close}><X /></button><span className="activity-number">{item?.[0]}</span><h2>{item?.[1]}</h2><p>{item?.[2]}</p><div className="coming-soon"><Sparkles /><strong>Esta estación se abre pronto</strong><span>Tu curso va a poder dejar su producción acá.</span></div><button className="primary-button" onClick={close}>VOLVER AL RECORRIDO</button></div></div> }

export function AxesView({ onBack, onQuiz }: { onBack: () => void; onQuiz: (id: EjeId) => void }) { return <div className="axes-view"><button className="back-link" onClick={onBack}><ArrowLeft /> Volver al recorrido</button><span className="section-kicker">LAS IDEAS QUE NOS MUEVEN</span><h2>Los 5 ejes<br /><em>de la ESI</em></h2><p className="muted">Cinco miradas para pensar nuestra escuela, nuestros vínculos y el futuro que queremos.</p><div className="axis-list">{ejes.map((eje, index) => <article key={eje.id} style={{ '--axis-color': eje.color } as React.CSSProperties}><span className="axis-big-number">0{index + 1}</span><span className="axis-symbol">{eje.icon}</span><div><h3>{eje.title}</h3><p>{eje.description}</p></div><button onClick={() => onQuiz(eje.id)}>Desafiar este eje <ArrowRight /></button></article>)}</div></div> }

export function TimelineView({ onBack }: { onBack: () => void }) { return <div className="timeline-view"><button className="back-link" onClick={onBack}><ArrowLeft /> Volver al recorrido</button><span className="section-kicker">MEMORIA + FUTURO</span><h2>20 años de<br /><em>ESI</em></h2><p className="muted">Una línea de tiempo para recordar, reconocer y proyectar.</p><div className="timeline">{timeline.map((item) => <article key={item.year}><span>{item.year}</span><div><h3>{item.title}</h3><p>{item.text}</p></div></article>)}</div></div> }

export function EsiRouter() { const [view, setView] = useState<'dashboard' | 'axes' | 'timeline'>('dashboard'); const [course] = useState('3°2'); return <main className="app-shell dashboard"><Header course={course} onHome={() => setView('dashboard')} onMenu={() => {}} />{view === 'axes' ? <AxesView onBack={() => setView('dashboard')} onQuiz={() => setView('dashboard')} /> : view === 'timeline' ? <TimelineView onBack={() => setView('dashboard')} /> : <div />}</main> }

export { AxesView, TimelineView }
